name: futurex_video_learning
description: A mini video learning app for FutureX technical challenge
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: 6.1.5

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # HTTP & Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Storage
  flutter_secure_storage: ^9.0.0

  # YouTube Player
  youtube_player_flutter: 9.1.3

  # UI
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0

  # Utils
  intl: ^0.18.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
